defmodule BeamWeaver.Models.ProfileRefresh do
  @moduledoc """
  Refreshes models.dev-style profile data into a BeamWeaver-native artifact.
  """

  alias BeamWeaver.Core.Error
  alias BeamWeaver.JSON
  alias BeamWeaver.Models.ProfileCompiler

  @api_url "https://models.dev/api.json"
  @artifact_name "profiles.json"
  @admonition """
  Auto-generated model profiles.

  DO NOT EDIT THIS FILE MANUALLY.
  This file is generated by BeamWeaver from models.dev-style data.
  """

  @doc """
  Refreshes one provider into `profiles.json` under `data_dir`.
  """
  @spec refresh(atom() | String.t(), Path.t(), keyword()) ::
          {:ok, %{path: Path.t(), profiles: [struct()]}} | {:error, Error.t()}
  def refresh(provider, data_dir, opts \\ []) do
    with {:ok, data_dir} <- validate_data_dir(data_dir, opts),
         {:ok, source_data} <- load_source_data(opts),
         {:ok, profiles} <- compile_profiles(provider, source_data, opts),
         :ok <- ensure_output_dir(data_dir),
         {:ok, output_path} <- write_profiles_file(data_dir, provider, profiles) do
      {:ok, %{path: output_path, profiles: profiles}}
    end
  end

  @doc """
  Validates a requested output directory and asks for confirmation when external.
  """
  @spec validate_data_dir(Path.t(), keyword()) :: {:ok, Path.t()} | {:error, Error.t()}
  def validate_data_dir(data_dir, opts \\ []) do
    cwd = opts |> Keyword.get(:cwd, File.cwd!()) |> Path.expand()
    data_dir = Path.expand(data_dir)

    cond do
      inside?(data_dir, cwd) ->
        {:ok, data_dir}

      Keyword.get(opts, :force, false) == true ->
        {:ok, data_dir}

      confirm_external_write?(data_dir, cwd, opts) ->
        {:ok, data_dir}

      true ->
        {:error,
         Error.new(:aborted, "refusing to write model profiles outside current directory", %{
           cwd: cwd,
           data_dir: data_dir
         })}
    end
  rescue
    exception ->
      {:error, Error.new(:invalid_path, Exception.message(exception), %{data_dir: data_dir})}
  end

  defp load_source_data(opts) do
    case Keyword.fetch(opts, :source_data) do
      {:ok, data} when is_map(data) ->
        {:ok, data}

      :error ->
        load_source_data_from_path_or_url(opts)

      {:ok, _invalid} ->
        {:error, Error.new(:invalid_source_data, "source_data must be a map")}
    end
  end

  defp load_source_data_from_path_or_url(opts) do
    case Keyword.fetch(opts, :source_path) do
      {:ok, path} ->
        path
        |> File.read()
        |> decode_json_source(path)

      :error ->
        fetch_source_url(Keyword.get(opts, :source_url, @api_url))
    end
  end

  defp decode_json_source({:ok, contents}, _path) do
    case BeamWeaver.JSON.decode(contents) do
      {:ok, data} when is_map(data) ->
        {:ok, data}

      {:ok, _invalid} ->
        {:error, Error.new(:invalid_source_data, "source JSON must decode to a map")}

      {:error, error} ->
        {:error, Error.new(:invalid_source_data, Exception.message(error))}
    end
  end

  defp decode_json_source({:error, reason}, path) do
    {:error,
     Error.new(:source_read_failed, "failed to read source data", %{
       path: Path.expand(path),
       reason: reason
     })}
  end

  defp fetch_source_url(url) do
    case Req.get(url, receive_timeout: 30_000) do
      {:ok, %{status: status, body: body}} when status in 200..299 and is_map(body) ->
        {:ok, body}

      {:ok, %{status: status}} ->
        {:error, Error.new(:source_fetch_failed, "models.dev request failed", %{status: status})}

      {:error, error} ->
        {:error, Error.new(:source_fetch_failed, Exception.message(error), %{url: url})}
    end
  end

  defp compile_profiles(provider, source_data, opts) do
    ProfileCompiler.compile_provider(source_data, provider,
      provider_overrides: Keyword.get(opts, :provider_overrides, %{}),
      model_overrides: Keyword.get(opts, :model_overrides, %{})
    )
  end

  defp ensure_output_dir(data_dir) do
    if symlink?(data_dir) do
      {:error, Error.new(:unsafe_output_path, "data directory is a symlink", %{path: data_dir})}
    else
      case File.mkdir_p(data_dir) do
        :ok ->
          :ok

        {:error, reason} ->
          {:error, Error.new(:write_failed, "failed to create data directory", %{reason: reason})}
      end
    end
  end

  defp write_profiles_file(data_dir, provider, profiles) do
    output_path = Path.join(data_dir, @artifact_name)

    with :ok <- ensure_regular_output(output_path),
         :ok <- atomic_write(output_path, artifact_json(provider, profiles)) do
      {:ok, output_path}
    end
  end

  defp ensure_regular_output(output_path) do
    if symlink?(output_path) do
      {:error, Error.new(:unsafe_output_path, "profiles artifact is a symlink", %{path: output_path})}
    else
      :ok
    end
  end

  defp atomic_write(output_path, contents) do
    temp_path =
      Path.join(
        Path.dirname(output_path),
        ".#{Path.basename(output_path)}.#{System.unique_integer([:positive])}.tmp"
      )

    case File.write(temp_path, contents) do
      :ok ->
        case File.rename(temp_path, output_path) do
          :ok ->
            :ok

          {:error, reason} ->
            File.rm(temp_path)

            {:error, Error.new(:write_failed, "failed to replace profiles artifact", %{reason: reason})}
        end

      {:error, reason} ->
        {:error, Error.new(:write_failed, "failed to write profiles artifact", %{reason: reason})}
    end
  end

  defp artifact_json(provider, profiles) do
    %{
      "admonition" => @admonition,
      "generated_by" => "BeamWeaver.Models.ProfileRefresh",
      "provider" => to_string(provider),
      "profiles" => Enum.map(profiles, &profile_json/1)
    }
    |> JSON.encode!(pretty: true)
    |> Kernel.<>("\n")
  end

  defp profile_json(profile) do
    profile
    |> Map.from_struct()
    |> normalize_json()
  end

  defp normalize_json(map) when is_map(map) do
    Map.new(map, fn {key, value} -> {to_string(key), normalize_json(value)} end)
  end

  defp normalize_json(values) when is_list(values), do: Enum.map(values, &normalize_json/1)
  defp normalize_json(nil), do: nil
  defp normalize_json(value) when is_boolean(value), do: value
  defp normalize_json(value) when is_atom(value), do: Atom.to_string(value)
  defp normalize_json(value), do: value

  defp inside?(path, cwd), do: path == cwd or String.starts_with?(path, cwd <> "/")

  defp confirm_external_write?(data_dir, cwd, opts) do
    confirm_fun = Keyword.get(opts, :confirm_fun, fn _target, _current -> false end)

    confirm_fun.(data_dir, cwd) == true
  end

  defp symlink?(path) do
    case File.lstat(path) do
      {:ok, %File.Stat{type: :symlink}} -> true
      _other -> false
    end
  end
end
