defmodule BeamWeaver.TextSplitter.Language do
  @moduledoc false

  alias BeamWeaver.TextSplitter.Shared

  @language_separators %{
    "c" => [
      "\nclass ",
      "\nvoid ",
      "\nint ",
      "\nfloat ",
      "\ndouble ",
      "\nif ",
      "\nfor ",
      "\nwhile ",
      "\nswitch ",
      "\ncase ",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "cpp" => [
      "\nclass ",
      "\nvoid ",
      "\nint ",
      "\nfloat ",
      "\ndouble ",
      "\nif ",
      "\nfor ",
      "\nwhile ",
      "\nswitch ",
      "\ncase ",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "go" => [
      "\nfunc ",
      "\nvar ",
      "\nconst ",
      "\ntype ",
      "\nif ",
      "\nfor ",
      "\nswitch ",
      "\ncase ",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "java" => [
      "\nclass ",
      "\npublic ",
      "\nprotected ",
      "\nprivate ",
      "\nstatic ",
      "\nif ",
      "\nfor ",
      "\nwhile ",
      "\nswitch ",
      "\ncase ",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "kotlin" => [
      "\nclass ",
      "\npublic ",
      "\nprotected ",
      "\nprivate ",
      "\ninternal ",
      "\ncompanion ",
      "\nfun ",
      "\nval ",
      "\nvar ",
      "\nif ",
      "\nfor ",
      "\nwhile ",
      "\nwhen ",
      "\nelse ",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "markdown" => [
      "\n\#{1,6} ",
      "```\n",
      "\n\\*\\*\\*+\n",
      "\n---+\n",
      "\n___+\n",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "html" => [
      "<body",
      "<div",
      "<p",
      "<br",
      "<li",
      "<h1",
      "<h2",
      "<h3",
      "<h4",
      "<h5",
      "<h6",
      "<span",
      "<table",
      "<tr",
      "<td",
      "<th",
      "<ul",
      "<ol",
      "<header",
      "<footer",
      "<nav",
      "<head",
      "<style",
      "<script",
      "<meta",
      "<title",
      ""
    ],
    "latex" => [
      "\n\\\\chapter{",
      "\n\\\\section{",
      "\n\\\\subsection{",
      "\n\\\\subsubsection{",
      "\n\\\\begin{enumerate}",
      "\n\\\\begin{itemize}",
      "\n\\\\begin{description}",
      "\n\\\\begin{list}",
      "\n\\\\begin{quote}",
      "\n\\\\begin{quotation}",
      "\n\\\\begin{verse}",
      "\n\\\\begin{verbatim}",
      "\n\\\\begin{align}",
      "$$",
      "$",
      " ",
      ""
    ],
    "python" => ["\nclass ", "\ndef ", "\n\tdef ", "\n\n", "\n", " ", ""],
    "javascript" => [
      "\nfunction ",
      "\nconst ",
      "\nlet ",
      "\nvar ",
      "\nclass ",
      "\nif ",
      "\nfor ",
      "\nwhile ",
      "\nswitch ",
      "\ncase ",
      "\ndefault ",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "typescript" => [
      "\nenum ",
      "\ninterface ",
      "\nnamespace ",
      "\ntype ",
      "\nclass ",
      "\nfunction ",
      "\nconst ",
      "\nlet ",
      "\nvar ",
      "\nif ",
      "\nfor ",
      "\nwhile ",
      "\nswitch ",
      "\ncase ",
      "\ndefault ",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "jsx" => ["\nfunction ", "\nconst ", "\nexport ", "\nreturn ", "\n\n", "\n", " ", ""],
    "tsx" => ["\nfunction ", "\nconst ", "\nexport ", "\nreturn ", "\n\n", "\n", " ", ""],
    "php" => [
      "\nfunction ",
      "\nclass ",
      "\nif ",
      "\nforeach ",
      "\nwhile ",
      "\ndo ",
      "\nswitch ",
      "\ncase ",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "proto" => [
      "\nmessage ",
      "\nservice ",
      "\nenum ",
      "\noption ",
      "\nimport ",
      "\nsyntax ",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "r" => [
      "\nfunction ",
      "\nsetClass\\(",
      "\nsetMethod\\(",
      "\nsetGeneric\\(",
      "\nif ",
      "\nelse ",
      "\nfor ",
      "\nwhile ",
      "\nrepeat ",
      "\nlibrary\\(",
      "\nrequire\\(",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "rst" => ["\n=+\n", "\n-+\n", "\n\\*+\n", "\n\n.. *\n\n", "\n\n", "\n", " ", ""],
    "ruby" => [
      "\ndef ",
      "\nclass ",
      "\nif ",
      "\nunless ",
      "\nwhile ",
      "\nfor ",
      "\ndo ",
      "\nbegin ",
      "\nrescue ",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "elixir" => [
      "\ndef ",
      "\ndefp ",
      "\ndefmodule ",
      "\ndefprotocol ",
      "\ndefmacro ",
      "\ndefmacrop ",
      "\nif ",
      "\nunless ",
      "\ncase ",
      "\ncond ",
      "\nwith ",
      "\nfor ",
      "\ndo ",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "rust" => [
      "\nfn ",
      "\nconst ",
      "\nlet ",
      "\nif ",
      "\nwhile ",
      "\nfor ",
      "\nloop ",
      "\nmatch ",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "scala" => [
      "\nclass ",
      "\nobject ",
      "\ndef ",
      "\nval ",
      "\nvar ",
      "\nif ",
      "\nfor ",
      "\nwhile ",
      "\nmatch ",
      "\ncase ",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "swift" => [
      "\nfunc ",
      "\nclass ",
      "\nstruct ",
      "\nenum ",
      "\nif ",
      "\nfor ",
      "\nwhile ",
      "\ndo ",
      "\nswitch ",
      "\ncase ",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "csharp" => [
      "\ninterface ",
      "\nenum ",
      "\ndelegate ",
      "\nevent ",
      "\nclass ",
      "\nabstract ",
      "\npublic ",
      "\nprotected ",
      "\nprivate ",
      "\nstatic ",
      "\nreturn ",
      "\nif ",
      "\ncontinue ",
      "\nfor ",
      "\nforeach ",
      "\nwhile ",
      "\nswitch ",
      "\nbreak ",
      "\ncase ",
      "\nelse ",
      "\ntry ",
      "\nthrow ",
      "\nfinally ",
      "\ncatch ",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "sol" => [
      "\npragma ",
      "\nusing ",
      "\ncontract ",
      "\ninterface ",
      "\nlibrary ",
      "\nconstructor ",
      "\ntype ",
      "\nfunction ",
      "\nevent ",
      "\nmodifier ",
      "\nerror ",
      "\nstruct ",
      "\nenum ",
      "\nif ",
      "\nfor ",
      "\nwhile ",
      "\ndo while ",
      "\nassembly ",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "cobol" => [
      "\nIDENTIFICATION DIVISION.",
      "\nENVIRONMENT DIVISION.",
      "\nDATA DIVISION.",
      "\nPROCEDURE DIVISION.",
      "\nWORKING-STORAGE SECTION.",
      "\nLINKAGE SECTION.",
      "\nFILE SECTION.",
      "\nINPUT-OUTPUT SECTION.",
      "\nOPEN ",
      "\nCLOSE ",
      "\nREAD ",
      "\nWRITE ",
      "\nIF ",
      "\nELSE ",
      "\nMOVE ",
      "\nPERFORM ",
      "\nUNTIL ",
      "\nVARYING ",
      "\nACCEPT ",
      "\nDISPLAY ",
      "\nSTOP RUN.",
      "\n",
      " ",
      ""
    ],
    "lua" => [
      "\nlocal ",
      "\nfunction ",
      "\nif ",
      "\nfor ",
      "\nwhile ",
      "\nrepeat ",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "haskell" => [
      "\nmain :: ",
      "\nmain = ",
      "\nlet ",
      "\nin ",
      "\ndo ",
      "\nwhere ",
      "\n:: ",
      "\n= ",
      "\ndata ",
      "\nnewtype ",
      "\ntype ",
      "\nmodule ",
      "\nimport ",
      "\nqualified ",
      "\nimport qualified ",
      "\nclass ",
      "\ninstance ",
      "\ncase ",
      "\n| ",
      "\n= {",
      "\n, ",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "powershell" => [
      "\nfunction ",
      "\nparam ",
      "\nif ",
      "\nforeach ",
      "\nfor ",
      "\nwhile ",
      "\nswitch ",
      "\nclass ",
      "\ntry ",
      "\ncatch ",
      "\nfinally ",
      "\n\n",
      "\n",
      " ",
      ""
    ],
    "visualbasic6" => [
      "\n(?!End\\s)(?:Public|Private|Friend|Global|Static)?\\s*Sub\\s+",
      "\n(?!End\\s)(?:Public|Private|Friend|Global|Static)?\\s*Function\\s+",
      "\n(?!End\\s)(?:Public|Private|Friend|Global|Static)?\\s*Property\\s+(?:Get|Let|Set)\\s+",
      "\n(?!End\\s)(?:Public|Private|Friend|Global|Static)?\\s*Type\\s+",
      "\n(?!End\\s)(?:Public|Private|Friend|Global|Static)?\\s*Enum\\s+",
      "\n(?!End\\s)If\\s+",
      "\nElseIf\\s+",
      "\nElse\\s+",
      "\nSelect\\s+Case\\s+",
      "\nCase\\s+",
      "\nFor\\s+",
      "\nDo\\s+",
      "\nWhile\\s+",
      "\nWith\\s+",
      "\n\n",
      "\n",
      " ",
      ""
    ]
  }

  def separators(language) do
    Map.get(@language_separators, normalize(language), Shared.common_fields()[:separators])
  end

  def normalize(language) when is_atom(language),
    do: language |> Atom.to_string() |> normalize()

  def normalize(language) when is_binary(language) do
    language
    |> String.downcase()
    |> String.replace(~r/[^a-z0-9]+/, "_")
    |> case do
      "py" -> "python"
      "js" -> "javascript"
      "ts" -> "typescript"
      "md" -> "markdown"
      "ex" -> "elixir"
      "exs" -> "elixir"
      "golang" -> "go"
      "c_plus_plus" -> "cpp"
      "csharp" -> "csharp"
      "c_sharp" -> "csharp"
      "solidity" -> "sol"
      "vb6" -> "visualbasic6"
      "visual_basic_6" -> "visualbasic6"
      "vue" -> "jsx"
      "svelte" -> "jsx"
      other -> other
    end
  end

  def normalize(_language), do: ""
end
