defmodule BeamWeaver.Models.ProfileRefreshTest do
  use ExUnit.Case, async: true

  alias BeamWeaver.Models.ProfileRefresh

  test "refresh aborts when user declines an external output directory" do
    root = tmp_dir("profile-refresh-root")
    external = tmp_dir("profile-refresh-external")
    data_dir = Path.join(external, "data")

    assert {:error, error} =
             ProfileRefresh.refresh("anthropic", data_dir,
               cwd: root,
               source_data: source_data(),
               confirm_fun: fn _target, _cwd -> false end
             )

    assert error.type == :aborted
    refute File.exists?(Path.join(data_dir, "profiles.json"))
  end

  test "refresh writes sorted BeamWeaver profile JSON from source data" do
    data_dir = tmp_dir("profile-refresh-data")

    assert {:ok, %{path: path, profiles: profiles}} =
             ProfileRefresh.refresh("anthropic", data_dir,
               source_data: source_data(),
               force: true,
               provider_overrides: %{image_url_inputs: true},
               model_overrides: %{"custom-offline-model" => %{structured_output: true}}
             )

    assert Enum.map(profiles, & &1.id) == ["claude-3-opus", "custom-offline-model"]
    assert path == Path.join(data_dir, "profiles.json")

    assert {:ok, artifact} = path |> File.read!() |> BeamWeaver.JSON.decode()
    assert artifact["provider"] == "anthropic"
    assert artifact["admonition"] =~ "DO NOT EDIT THIS FILE MANUALLY"
    assert Enum.map(artifact["profiles"], & &1["id"]) == ["claude-3-opus", "custom-offline-model"]
    assert Enum.all?(artifact["profiles"], &(&1["image_url_inputs"] == true))
  end

  test "refresh fails without writing when provider is absent" do
    data_dir = tmp_dir("profile-refresh-missing")

    assert {:error, error} =
             ProfileRefresh.refresh("missing-provider", data_dir,
               source_data: source_data(),
               force: true
             )

    assert error.type == :missing_profile_provider
    refute File.exists?(Path.join(data_dir, "profiles.json"))
  end

  test "refresh works without overrides" do
    data_dir = tmp_dir("profile-refresh-no-overrides")

    assert {:ok, %{path: path, profiles: [%{id: "claude-3-opus"}]}} =
             ProfileRefresh.refresh("anthropic", data_dir,
               source_data: source_data(),
               force: true
             )

    assert File.exists?(path)
  end

  defp source_data do
    %{
      "anthropic" => %{
        "id" => "anthropic",
        "models" => %{
          "claude-3-opus" => %{
            "id" => "claude-3-opus",
            "name" => "Claude 3 Opus",
            "tool_call" => true,
            "limit" => %{"context" => 200_000, "output" => 4_096},
            "modalities" => %{"input" => ["text", "image"], "output" => ["text"]}
          }
        }
      }
    }
  end

  defp tmp_dir(name) do
    path = Path.join(System.tmp_dir!(), "#{name}-#{System.unique_integer([:positive])}")
    File.mkdir_p!(path)
    on_exit(fn -> File.rm_rf(path) end)
    path
  end
end
