defmodule BeamWeaver.Models.ProfileRegistry.Params do
  @moduledoc false

  @responses_params [
    :audio,
    :background,
    :conversation,
    :context_management,
    :frequency_penalty,
    :include,
    :instructions,
    :max_output_tokens,
    :max_tool_calls,
    :metadata,
    :modalities,
    :parallel_tool_calls,
    :previous_response_id,
    :prompt,
    :prompt_cache_key,
    :prompt_cache_retention,
    :reasoning,
    :reasoning_effort,
    :response_format,
    :safety_identifier,
    :seed,
    :service_tier,
    :store,
    :stream,
    :stream_options,
    :structured_output,
    :temperature,
    :text,
    :tool_choice,
    :tools,
    :top_logprobs,
    :top_p,
    :truncation,
    :user,
    :verbosity
  ]

  @chat_completions_params [
    :audio,
    :frequency_penalty,
    :function_call,
    :functions,
    :logit_bias,
    :logprobs,
    :max_completion_tokens,
    :max_tokens,
    :metadata,
    :modalities,
    :n,
    :parallel_tool_calls,
    :prediction,
    :presence_penalty,
    :prompt_cache_key,
    :prompt_cache_retention,
    :reasoning_effort,
    :response_format,
    :safety_identifier,
    :seed,
    :service_tier,
    :stop,
    :store,
    :stream,
    :stream_options,
    :structured_output,
    :temperature,
    :tool_choice,
    :tools,
    :top_logprobs,
    :top_p,
    :user,
    :verbosity,
    :web_search_options
  ]

  @embedding_params [:dimensions, :encoding_format, :user]

  @anthropic_params [
    :betas,
    :cache_control,
    :container,
    :context_management,
    :diagnostics,
    :effort,
    :inference_geo,
    :max_output_tokens,
    :max_tokens,
    :metadata,
    :mcp_servers,
    :output_config,
    :parallel_tool_calls,
    :response_format,
    :service_tier,
    :speed,
    :stop,
    :stop_sequences,
    :stream,
    :stream_usage,
    :structured_output,
    :temperature,
    :thinking,
    :tool_choice,
    :tools,
    :top_k,
    :top_p,
    :user_profile_id
  ]

  @xai_responses_params [
    :context_management,
    :include,
    :instructions,
    :max_output_tokens,
    :max_tokens,
    :max_turns,
    :parallel_tool_calls,
    :previous_response_id,
    :prompt_cache_key,
    :reasoning,
    :reasoning_effort,
    :response_format,
    :search_parameters,
    :store,
    :stream,
    :structured_output,
    :temperature,
    :text,
    :tool_choice,
    :tools,
    :top_p,
    :truncation,
    :use_previous_response_id,
    :user
  ]

  @xai_chat_completions_params [
    :deferred,
    :frequency_penalty,
    :max_completion_tokens,
    :max_tokens,
    :n,
    :parallel_tool_calls,
    :presence_penalty,
    :reasoning_effort,
    :response_format,
    :search_parameters,
    :seed,
    :stop,
    :stream,
    :stream_options,
    :stream_usage,
    :structured_output,
    :temperature,
    :tool_choice,
    :tools,
    :top_p,
    :user,
    :web_search_options
  ]

  @xai_embedding_params [:dimensions, :encoding_format, :preview, :user]

  @moonshot_params [
    :frequency_penalty,
    :max_completion_tokens,
    :max_output_tokens,
    :max_tokens,
    :n,
    :presence_penalty,
    :prompt_cache_key,
    :response_format,
    :safety_identifier,
    :stop,
    :stream,
    :stream_options,
    :stream_usage,
    :structured_output,
    :temperature,
    :thinking,
    :tool_choice,
    :tools,
    :top_p
  ]

  @zai_params [
    :do_sample,
    :max_completion_tokens,
    :max_output_tokens,
    :max_tokens,
    :metadata,
    :model_kwargs,
    :reasoning_effort,
    :request_id,
    :response_format,
    :stop,
    :stream,
    :stream_options,
    :stream_usage,
    :structured_output,
    :temperature,
    :thinking,
    :tool_choice,
    :tool_stream,
    :tools,
    :top_p,
    :user_id
  ]

  @google_params [
    :cached_content,
    :candidate_count,
    :code_execution,
    :enable_enhanced_civic_answers,
    :extra_body,
    :frequency_penalty,
    :generation_config,
    :image_config,
    :include_thoughts,
    :include_server_side_tool_invocations,
    :labels,
    :logprobs,
    :max_output_tokens,
    :media_resolution,
    :model_kwargs,
    :presence_penalty,
    :response_format,
    :response_format_config,
    :response_json_schema,
    :response_logprobs,
    :response_mime_type,
    :response_modalities,
    :response_schema,
    :retrieval_config,
    :safety_settings,
    :seed,
    :service_tier,
    :speech_config,
    :stop,
    :stop_sequences,
    :store,
    :stream,
    :structured_output,
    :temperature,
    :thinking_budget,
    :thinking_level,
    :tool_config,
    :tool_choice,
    :tools,
    :top_k,
    :top_p
  ]

  def responses, do: @responses_params
  def chat_completions, do: @chat_completions_params
  def embedding, do: @embedding_params
  def anthropic, do: @anthropic_params
  def xai_responses, do: @xai_responses_params
  def xai_chat_completions, do: @xai_chat_completions_params
  def xai_embedding, do: @xai_embedding_params
  def moonshot, do: @moonshot_params
  def zai, do: @zai_params
  def google, do: @google_params
end
